#业务应用配置  优先加载，可以重写 health_core 配置文件信息
server:
  port: 8909
spring:
  application:
    name: appo-application #应用名称
xxl:
  job:
    enabled: true    # xxl-job开关
    executor:
      appname: health-executor
      port: -1
      logpath: /Volumes/Worker/Tools/xxl-job-2.0.1/data/logs   #  chmod  777
      logretentiondays: -1
    admin:
      addresses: http://localhost:8091/xxl-job-admin